[package]
name = "sccache"
version = "0.1.1-pre"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "Apache-2.0"
description = "Sccache is a ccache-like tool. It is used as a compiler wrapper and avoids compilation when possible, storing a cache in a remote storage using the S3 API."
repository = "https://github.com/mozilla/sccache/"


[dependencies]
app_dirs = "1.1.1"
bincode = { git = 'https://github.com/TyOverby/bincode' }
byteorder = "1.0"
toml = "0.4"
chrono = { version = "0.2.25", optional = true }
clap = "~2.23.0"
env_logger = "0.3.3"
error-chain = { version = "0.7.2", default-features = false }
fern = "0.3.5"
filetime = "0.1"
futures = "0.1.11"
futures-cpupool = "0.1"
hyper = { git = "https://github.com/hyperium/hyper", optional = true }
hyper-tls = { git = "https://github.com/hyperium/hyper-tls", optional = true }
lazy_static = "0.2"
libc = "0.2.10"
local-encoding = "0.2.0"
log = "0.3.6"
lru-disk-cache = { path = "lru-disk-cache" }
number_prefix = "0.2.5"
redis = { version = "0.8.0", optional = true }
regex = "0.1.65"
retry = "0.4.0"
ring = "0.9.0"
rust-crypto = { version = "0.2.36", optional = true }
rustc-serialize = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
tempdir = "0.3.4"
time = "0.1.35"
tokio-core = "0.1.6"
tokio-io = "0.1"
tokio-process = "0.1"
tokio-proto = "0.1"
tokio-serde-bincode = { git = "https://github.com/alexcrichton/tokio-serde-bincode" }
tokio-service = "0.1"
tokio-tls = "0.1"
uuid = { version = "0.3.1", features = ["v4"] }
which = "0.2.1"
zip = { version = "0.2", default-features = false }

[dev-dependencies]
gcc = "0.3"
itertools = "0.5.10"

[target.'cfg(unix)'.dependencies]
daemonize = "0.2.3"
tokio-uds = "0.1"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.2"
mio-named-pipes = "0.1"

[features]
default = ["s3"]
all = ["redis", "s3"]
s3 = ["chrono", "hyper", "hyper-tls", "rust-crypto", "simple-s3"]
simple-s3 = []
# Enable features that require unstable features of Nightly Rust.
unstable = []

[profile.release]
debug = true

[workspace]
